### ISSUE TITLE
Confusing EXIT_PERIOD_SECONDS -> MIN_EXIT_PERIOD

### ISSUE THREAD

**Issue by kevsul** [omisego/plasma-deployer#7]
The plasma-deployer code uses  EXIT_PERIOD_SECONDS env var to set MIN_EXIT_PERIOD var for the contracts.

Would be better to rename it to MIN_EXIT_PERIOD to be consistent

https://github.com/omisego/plasma-deployer/blob/32e80582cfdce179ddd49b0344fb6c43ff896f5c/lib/plasma_deployer/deploy.ex#L23

**Comment by jrhite** [comment]
I totally agree on the consistency thing. One thing I do like about plasma-deployers name is it has units in the variable name, so we don't have to guess is it millis or seconds, etc...

**Comment by boolafish** [comment]
hmmm......but contract is not taking env var for min exit period. It uses its own config now:

https://github.com/omisego/plasma-contracts/blob/d086e3e68e227d8e2f64aba9726d1e49ab2ff31f/plasma_framework/migrations/config.js#L7

**Comment by kevsul** [comment]
My bad, this is not even used anymore
